import 'package:flutter/material.dart';

final ThemeData roomieTheme = ThemeData(
  primaryColor: const Color.fromRGBO(98, 212, 123, 1),
  primaryColorDark: const Color.fromRGBO(34, 35, 44, 1),
  primaryColorLight: const Color.fromRGBO(91, 92, 98, 1),
  splashColor: const Color.fromRGBO(216, 216, 216, 1),
  backgroundColor: const Color.fromRGBO(53, 54, 68, 1),
  hoverColor: const Color.fromRGBO(34, 35, 44, 1),
  disabledColor: const Color.fromRGBO(67, 107, 86, 1),
  hintColor: const Color.fromRGBO(154, 154, 154, 1),
  secondaryHeaderColor: const Color.fromRGBO(23, 24, 30, 1),
//  textSelectionHandleColor:
//  highlightColor: const Color.fromRGBO(130, 218, 251, 0.15),
//  splashColor: const Color.fromRGBO(0, 0, 0, 0.2),
//  buttonColor: const Color.fromRGBO(253, 187, 94, 1),
//  textSelectionColor: const Color.fromRGBO(51, 70, 89, 1),
//  cursorColor: const Color.fromRGBO(0, 0, 0, 0.1),
//  dialogBackgroundColor: const Color.fromRGBO(51, 70, 89, 0.8),
//  hintColor: const Color.fromRGBO(51, 70, 89, 0.7),
//  accentColor: const Color.fromRGBO(51, 70, 89, 0.65),
//  errorColor: const Color.fromRGBO(255, 117, 105, 1),
//  cardColor: const Color.fromRGBO(239, 239, 244, 1),
//  focusColor: const Color.fromRGBO(34, 35, 44, 1),
  textTheme: TextTheme(
    button: TextStyle(
      color: Color.fromRGBO(255, 255, 255, 1),
      fontFamily: 'Helvetica Neue',
      fontSize: 18.0,
      letterSpacing: 0.59,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.normal,
    ),
//    headline: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 14.0,
//      letterSpacing: 0.4375,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.w600,
//    ),
//    title: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 17.0,
//      letterSpacing: 0.41,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.w600,
//    ),
//    subtitle: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 16.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.normal,
//    ),
//    body1: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 14.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.w600,
//    ),
//    body2: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 15.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.normal,
//    ),
//    display1: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 15.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.w500,
//    ),
//    display2: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 16.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.normal,
//    ),
//    display3: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 14.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.normal,
//    ),
//    display4: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 16.0,
//      fontStyle: FontStyle.normal,
//      fontWeight: FontWeight.normal,
//    ),
    caption: TextStyle(
      color: Color.fromRGBO(154, 154, 154, 1),
      fontFamily: 'Helvetica Neue',
      fontSize: 16.0,
      fontWeight: FontWeight.normal,
    ),
//
//    overline: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 12.0,
//      fontWeight: FontWeight.w500,
//      letterSpacing: 0.4,
//    ),
//    subhead: TextStyle(
//      color: Color.fromRGBO(216, 216, 216, 1),
//      fontFamily: 'Helvetica Neue',
//      fontSize: 16.0,
//      fontWeight: FontWeight.normal,
//    ),
  ),
);
